/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SupplyandDemandRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.FurnitureMakingOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FurnitureMakingRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class FurnitureRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form RequestLabTestJPanel
     */
    public FurnitureRequestJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameJTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        phoneNumberJTextField1 = new javax.swing.JTextField();
        dimensionJTextField3 = new javax.swing.JTextField();
        emailJTextField4 = new javax.swing.JTextField();
        addressJTextField6 = new javax.swing.JTextField();
        FurnitureTypejComboBox = new javax.swing.JComboBox();
        woodTypejComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        qunatityJTextField5 = new javax.swing.JTextField();
        enterpriseLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 252, 241));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submitJButton.setBackground(new java.awt.Color(31, 40, 51));
        submitJButton.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(255, 255, 255));
        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, -1, -1));

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel1.setText("Email id");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 80, -1));

        backJButton.setBackground(new java.awt.Color(31, 40, 51));
        backJButton.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));

        valueLabel.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 160, 30));

        enterpriseLabel.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        enterpriseLabel.setText("Furniture Making Request Form");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 250, 30));

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel2.setText("Address");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, 20));

        nameJTextField1.setBackground(new java.awt.Color(31, 40, 51));
        nameJTextField1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        nameJTextField1.setForeground(new java.awt.Color(255, 255, 255));
        add(nameJTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 89, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel3.setText("Wood Type");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, 20));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel4.setText("Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, 20));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel5.setText("Phone Number");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, 20));

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel6.setText("Furniture Type");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, 20));

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel7.setText("Dimensions");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 80, -1));

        phoneNumberJTextField1.setBackground(new java.awt.Color(31, 40, 51));
        phoneNumberJTextField1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        phoneNumberJTextField1.setForeground(new java.awt.Color(255, 255, 255));
        add(phoneNumberJTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 89, -1));

        dimensionJTextField3.setBackground(new java.awt.Color(31, 40, 51));
        dimensionJTextField3.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        dimensionJTextField3.setForeground(new java.awt.Color(255, 255, 255));
        dimensionJTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimensionJTextField3ActionPerformed(evt);
            }
        });
        add(dimensionJTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 89, -1));

        emailJTextField4.setBackground(new java.awt.Color(31, 40, 51));
        emailJTextField4.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        emailJTextField4.setForeground(new java.awt.Color(255, 255, 255));
        add(emailJTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 89, -1));

        addressJTextField6.setBackground(new java.awt.Color(31, 40, 51));
        addressJTextField6.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        addressJTextField6.setForeground(new java.awt.Color(255, 255, 255));
        add(addressJTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 89, -1));

        FurnitureTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Study Table", "Chair", "Dining Table", "Book Case ", "Head Board" }));
        FurnitureTypejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FurnitureTypejComboBoxActionPerformed(evt);
            }
        });
        add(FurnitureTypejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 90, -1));

        woodTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Oak", "Maple", "Walnut", "Mahogany", "Rose Wood" }));
        add(woodTypejComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 90, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel8.setText("Quantity");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 80, -1));

        qunatityJTextField5.setBackground(new java.awt.Color(31, 40, 51));
        qunatityJTextField5.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        qunatityJTextField5.setForeground(new java.awt.Color(255, 255, 255));
        add(qunatityJTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 89, -1));

        enterpriseLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        enterpriseLabel1.setText("EnterPrise :");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 170, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        
        String name= nameJTextField1.getText();
        String phone=phoneNumberJTextField1.getText();
        String Address=addressJTextField6.getText();
        String furniture=FurnitureTypejComboBox.getSelectedItem().toString();
        String wood=woodTypejComboBox.getSelectedItem().toString();
        String dimensions=dimensionJTextField3.getText();
        String quantity=qunatityJTextField5.getText();
        String email = emailJTextField4.getText();
        Random rand = new Random(); 
        int rand_int1 = rand.nextInt(1000); 
        if("".equals(Address)){
            JOptionPane.showMessageDialog(null,"Fill all the Fields!!");
            return;
        }
        if("".equals(name)&&"".equals(phone)&&"".equals(dimensions)&&"".equals(quantity)){
            JOptionPane.showMessageDialog(null,"Please Fill all the Fields!!");
            return;
        }
        String nameregex="^[a-zA-Z]+$";
        if(!name.matches(nameregex)){
            JOptionPane.showMessageDialog(null,"Name Field accepts only Alphabets");
            return;
        }
        String phoneregex="^[0-9]{3}-[0-9]{3}-[0-9]{4}$";
        if(!phone.matches(phoneregex)){
            JOptionPane.showMessageDialog(null,"Phone Number should be in number format xxx-xxx-xxxx");
            return;
        }
        String Dimensionregex="(^[0-9]{2}x[0-9]{2}x[0-9]{2}$)";
        if(!dimensions.matches(Dimensionregex)){
            JOptionPane.showMessageDialog(null,"Dimensions accepts only numbers with format llxbbxhh");
            return;
        }
        String qtyregex="^[0-9]+$";
        if(!quantity.matches(qtyregex)){
            JOptionPane.showMessageDialog(null,"Quantity accepts only numbers");
            return;
        }
        String emailregex="^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$";
        if(!email.matches(emailregex)){
            JOptionPane.showMessageDialog(null,"Enter valid Email!!");
            return;
        }
        FurnitureMakingRequest request = new FurnitureMakingRequest();
        request.setOrder(rand_int1);
        request.setName(name);
        request.setPhoneNumber(phone);
        request.setAddress(Address);
        request.setFurnitureType(furniture);
        request.setWoodType(wood);
        request.setDimension(dimensions);
        request.setQuantity(quantity);
        request.setSender(userAccount);
        request.setEmail(email);
        request.setStatus("Ready to be processed");
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof FurnitureMakingOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        JOptionPane.showMessageDialog(null, "Order Placed Successfully!!");
        String mailer1 = request.getEmail();
        int mailerorder = request.getOrder();
        String mailerft = "FurnitureType:"+request.getFurnitureType()+"\n "+"Order Number:" +mailerorder;
        
        Mailer.send("urbanhelpera@gmail.com","Welcome@123",mailer1,"Furniture Request", mailerft); 
        
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        supplyAndDemandWorkAreaJPanel dwjp = (supplyAndDemandWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void FurnitureTypejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FurnitureTypejComboBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_FurnitureTypejComboBoxActionPerformed

    private void dimensionJTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimensionJTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dimensionJTextField3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox FurnitureTypejComboBox;
    private javax.swing.JTextField addressJTextField6;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField dimensionJTextField3;
    private javax.swing.JTextField emailJTextField4;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nameJTextField1;
    private javax.swing.JTextField phoneNumberJTextField1;
    private javax.swing.JTextField qunatityJTextField5;
    private javax.swing.JButton submitJButton;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JComboBox woodTypejComboBox;
    // End of variables declaration//GEN-END:variables
}
