/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageFlights;

import Business.Airliner.*;
import Business.TravelAgency.TravelAgency;
import UserInterface.ManageAirliners.ManageAirlinersJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author vaibhavdhoke
 */
public class AddFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddFlightJPanel
     */
    private JPanel container;
    private Airliner airliner;
    public AddFlightJPanel(JPanel container,Airliner airliner) {
        initComponents();
        this.container=container;
        this.airliner=airliner;
         
        List<Airplane> airplane= airliner.getAirplane();
        
        
        for(Airplane a:airplane){
        comboAirliner.addItem(a.getPlaneNumber());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboAirliner = new javax.swing.JComboBox<>();
        txtDateField = new javax.swing.JTextField();
        txtDestiField = new javax.swing.JTextField();
        txtSourceField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox<>();
        btnSchedule = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(203, 238, 249));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Schedule Flight");

        jLabel2.setText("Source");

        jLabel3.setText("Destination:");

        jLabel4.setText("Date:");

        jLabel5.setText("Aircraft");

        comboAirliner.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        txtDestiField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestiFieldActionPerformed(evt);
            }
        });

        txtSourceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSourceFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Status:");

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Ontime", "Cancelled" }));

        btnSchedule.setBackground(new java.awt.Color(153, 255, 255));
        btnSchedule.setText("Schedule");
        btnSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScheduleActionPerformed(evt);
            }
        });

        jLabel7.setText("Price:");

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnBack)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtSourceField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                        .addComponent(txtDestiField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtDateField, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtPrice, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnSchedule, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(421, 421, 421))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSourceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDestiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSchedule)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSourceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSourceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSourceFieldActionPerformed

    private void txtDestiFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestiFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestiFieldActionPerformed

    private void btnScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScheduleActionPerformed
        // TODO add your handling code here:
        
        
        
        String source= txtSourceField.getText();
        String desti = txtDestiField.getText();
        String date= txtDateField.getText();
        String selAircraft = comboAirliner.getSelectedItem().toString();
        
        if(!source.matches("^[a-zA-Z]*$")||source.equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the valid input for Source");
            return;
        }
        if(!desti.matches("^[a-zA-Z]*$")||desti.equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the valid input for Destination");
            return;
        }
        
        if (!date.matches("\\d{2}-\\d{2}-\\d{4}")) {
            JOptionPane.showMessageDialog(null,"Date should in format DD-MM-YYYY");
            return;
        }
        
        if(comboAirliner.getSelectedIndex()==0){
         JOptionPane.showMessageDialog(null,"Please select AirCraft");
         return;
        }
        
        if(comboStatus.getSelectedIndex()==0){
         JOptionPane.showMessageDialog(null,"Please select status");
         return;
        }
        
        if(!txtPrice.getText().matches("[0-9]+")){
          JOptionPane.showMessageDialog(null,"Please enter number for price");
          return;
        }
        
        
        
        List<Airplane> airplane=airliner.getAirplane();
        Boolean status=true;
        if(comboStatus.getSelectedItem().toString().equalsIgnoreCase("Cancelled")){
        
        status=true;
        }else if(comboStatus.getSelectedItem().toString().equalsIgnoreCase("Ontime")){
       
        status=false;
        }
       
                
        for(Airplane ap:airplane){
            if(ap.getPlaneNumber().equalsIgnoreCase(selAircraft)){
            
            airliner.getFlightSchedule().addFlight(ap, source, desti, date, status,Integer.parseInt(txtPrice.getText()));
            }
        }
        
        
        JOptionPane.showMessageDialog(null, "Flight successfully scheduled for "+airliner.getAirlinerName());
        
    }//GEN-LAST:event_btnScheduleActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout)container.getLayout();
        Component[] comps = container.getComponents();
        for(Component comp :comps){
            if(comp instanceof ManageAirlinersJPanel){
                ManageAirlinersJPanel managep=(ManageAirlinersJPanel)comp;
                managep.populateTable();
            }
        }
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSchedule;
    private javax.swing.JComboBox<String> comboAirliner;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtDateField;
    private javax.swing.JTextField txtDestiField;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSourceField;
    // End of variables declaration//GEN-END:variables
}
