/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Business.Airliner.Airliner;
import Business.Airliner.AirlinerDirectory;
import Business.Airliner.Airplane;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class ManageAirlinersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirlinersJPanel
     */
    private JPanel container;
    private AirlinerDirectory linerDir;

    public ManageAirlinersJPanel(JPanel container,AirlinerDirectory linerDir) {
        initComponents();
        this.container=container;
        this.linerDir=linerDir;
        populateTable();
        
    }
    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) airlinerjtable.getModel();
    dtm.setRowCount(0);
    for(Airliner air : linerDir.getAirlinerList()){
        Object[] row = new Object[3];
        row[0]= air;
        row[1]=air.getAddress();
        dtm.addRow(row); 
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        airlinerjtable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAirplane = new javax.swing.JTable();
        btnAircraft = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(203, 238, 249));

        viewBtn.setBackground(new java.awt.Color(0, 204, 204));
        viewBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewBtn.setText("View Airliner");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("New Airliner");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        airlinerjtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner Name", "Address"
            }
        ));
        jScrollPane1.setViewportView(airlinerjtable);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Manage Airliners");

        tblAirplane.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner", "Aircraft Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblAirplane);
        if (tblAirplane.getColumnModel().getColumnCount() > 0) {
            tblAirplane.getColumnModel().getColumn(0).setResizable(false);
            tblAirplane.getColumnModel().getColumn(1).setResizable(false);
        }

        btnAircraft.setBackground(new java.awt.Color(0, 255, 204));
        btnAircraft.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnAircraft.setText("View Aircraft");
        btnAircraft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAircraftActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(0, 255, 204));
        btnAdd.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnAdd.setText("Add Airplane");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setText("Airplanes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnBack))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(viewBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAircraft, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel2)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnBack)
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewBtn)
                        .addGap(45, 45, 45)
                        .addComponent(jButton2)))
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAircraft)
                        .addGap(43, 43, 43)
                        .addComponent(btnAdd)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CreateNewAirlinerJPanel panel  = new CreateNewAirlinerJPanel(container,linerDir);
        container.add("CreateNewAirlinerJPanel",panel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout)container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow= airlinerjtable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"please select a row from from the table to view details","warning",JOptionPane.ERROR_MESSAGE);
          }
        
        else{
            Airliner airliner =  (Airliner) airlinerjtable.getValueAt(selectedRow, 0);
            
            ViewAirlinerJPanel viewAirlinerJPanel = new ViewAirlinerJPanel(container, airliner);
            container.add("ViewAirlinerJPanel",viewAirlinerJPanel);
           CardLayout layout=(CardLayout) container.getLayout();
           layout.next(container);
        }
    }//GEN-LAST:event_viewBtnActionPerformed

    private void btnAircraftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAircraftActionPerformed
        // TODO add your handling code here:
        int selectedRow= airlinerjtable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"please select a row from from the table to view details","warning",JOptionPane.ERROR_MESSAGE);
          }
        
        else{
            Airliner airliner =  (Airliner) airlinerjtable.getValueAt(selectedRow, 0);
            DefaultTableModel dtm = (DefaultTableModel) airlinerjtable.getModel();
            DefaultTableModel tblairplane=  (DefaultTableModel) tblAirplane.getModel();
            tblairplane.setRowCount(0);
        for(Airplane A: airliner.getAirplane()){
            Object[] row = new Object[3];
            row[0]= A.getAirlinerName();
            row[1]=A.getPlaneNumber();
            tblairplane.addRow(row);
            }
        }
        
    }//GEN-LAST:event_btnAircraftActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        int selectedRow= airlinerjtable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"please select the Airliner for which your are trying to add airplane","warning",JOptionPane.ERROR_MESSAGE);
          }
        else{
        Airliner airliner =  (Airliner) airlinerjtable.getValueAt(selectedRow, 0);
        AddairplaneJPanel addAirplane= new AddairplaneJPanel(container, airliner);
        container.add("AddairplaneJPanel",addAirplane);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnAddActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable airlinerjtable;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAircraft;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAirplane;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables

    
}
