/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BookTicket;

import Business.Airliner.Flight;
import Business.Airliner.FlightSchedule;
import Business.Airliner.Seat;
import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import UserInterface.ManageAirliners.ManageAirlinersJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Surya
 */
public class BookedCustomerHistory extends javax.swing.JPanel {

    /**
     * Creates new form BookedCustomerHistory
     */
    private JPanel container;
    private CustomerDirectory customerDirectory;
    public BookedCustomerHistory(JPanel container,CustomerDirectory customerDirectory) {
        initComponents();
        this.container=container;
        this.customerDirectory=customerDirectory;
        populate();
    }

     public void populate(){
        DefaultTableModel dtm= (DefaultTableModel)tblCustomerBooked.getModel();
        dtm.setRowCount(0);
        List<Customer> list = new ArrayList<>();
        list= customerDirectory.getCustomerList();
        
        for(Customer  fs:list){
            //f=fs.getFlightSchedule();
            
                List<Seat> l= fs.getSeatList();
                for(int j=0;j<l.size();j++){
                    Object[] row = new Object[7];
                
                    row[0] = fs.getCustomerName();
                    row[1] = fs.getFlight().getAirplane().getAirlinerName();
                    row[2] = fs.getFlight().getLocationFrom();
                    row[3] = fs.getFlight().getLocationTo();
                    row[4] = fs.getFlight().getDate();
                    row[5] = fs.getFlight().getAirplane().getPlaneNumber();
                    row[6] = l.get(j).getActualSeat();
                    dtm.addRow(row);
                }
                
            
        }
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomerBooked = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(203, 238, 249));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Booked History");

        tblCustomerBooked.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Airliner", "Source", "Destination", "Date", "Aircraft", "Seat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCustomerBooked);
        if (tblCustomerBooked.getColumnModel().getColumnCount() > 0) {
            tblCustomerBooked.getColumnModel().getColumn(0).setResizable(false);
            tblCustomerBooked.getColumnModel().getColumn(1).setResizable(false);
            tblCustomerBooked.getColumnModel().getColumn(2).setResizable(false);
            tblCustomerBooked.getColumnModel().getColumn(3).setResizable(false);
            tblCustomerBooked.getColumnModel().getColumn(4).setResizable(false);
            tblCustomerBooked.getColumnModel().getColumn(5).setResizable(false);
            tblCustomerBooked.getColumnModel().getColumn(6).setResizable(false);
        }

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(382, 382, 382))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(360, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout)container.getLayout();
        Component[] comps = container.getComponents();
        for(Component comp :comps){
            if(comp instanceof ManageAirlinersJPanel){
                ManageAirlinersJPanel managep=(ManageAirlinersJPanel)comp;
                managep.populateTable();
            }
        }
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCustomerBooked;
    // End of variables declaration//GEN-END:variables
}
