/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface;
import UserInterface.BookTicket.MasterSchedule;
//import Business.Airliner.FlightSchedule;
import java.awt.CardLayout;
import Business.TravelAgency.MasterTravelSchedule;

import Business.Airliner.*;
import Business.TravelAgency.*;
import UserInterface.BookTicket.BookedCustomerHistory;

import UserInterface.ManageFlights.ManageFlightJPanel;

import UserInterface.BookTicket.BookedCustomerHistory;
import UserInterface.BookTicket.MasterSchedule;
import UserInterface.ManageAirliners.ManageAirlinersJPanel;

/**
 *
 * @author admin
 */
public class TravelAgencyJFrame extends javax.swing.JFrame {

    /**
     * Creates new form travelAgencyJFrame
     */
    private TravelAgency travelAgency;
    public TravelAgencyJFrame() {
        initComponents();
        travelAgency= new TravelAgency();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnManageAirliners = new javax.swing.JButton();
        bookBtn = new javax.swing.JButton();
        btnTciketHistory = new javax.swing.JButton();
        btnMngFlights = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(154, 238, 249));

        btnManageAirliners.setBackground(new java.awt.Color(167, 205, 249));
        btnManageAirliners.setText("Manage Airliners");
        btnManageAirliners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAirlinersActionPerformed(evt);
            }
        });

        bookBtn.setBackground(new java.awt.Color(0, 204, 204));
        bookBtn.setText("Book Ticket");
        bookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBtnActionPerformed(evt);
            }
        });

        btnTciketHistory.setBackground(new java.awt.Color(255, 204, 204));
        btnTciketHistory.setText("Ticket History");
        btnTciketHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTciketHistoryActionPerformed(evt);
            }
        });

        btnMngFlights.setBackground(new java.awt.Color(0, 255, 204));
        btnMngFlights.setText("Manage Flights");
        btnMngFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngFlightsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManageAirliners, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMngFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(bookBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTciketHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnManageAirliners, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnMngFlights)
                .addGap(55, 55, 55)
                .addComponent(bookBtn)
                .addGap(62, 62, 62)
                .addComponent(btnTciketHistory)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        container.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/flight.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jLabel1.setMinimumSize(new java.awt.Dimension(900, 600));
        container.add(jLabel1, "card2");

        jSplitPane1.setRightComponent(container);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1052, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageAirlinersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAirlinersActionPerformed
           // TODO add your handling code here:
           ManageAirlinersJPanel manageAirLiners= new ManageAirlinersJPanel(container, travelAgency.getAirlinerDirectory());
           container.add("ManageAirlinersJPanel",manageAirLiners);
           CardLayout layout=(CardLayout) container.getLayout();
           layout.next(container);
    }//GEN-LAST:event_btnManageAirlinersActionPerformed

    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtnActionPerformed
        // TODO add your handling code here:
        MasterSchedule master= new MasterSchedule(container,travelAgency);
        container.add("MasterSchedule", master);
        CardLayout layout= (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_bookBtnActionPerformed

    private void btnTciketHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTciketHistoryActionPerformed
        // TODO add your handling code here:
    BookedCustomerHistory bookedCustomerHistory = new BookedCustomerHistory(container,travelAgency.getTravelOffice().getCustomerDirectory());
    container.add("BookedCustomerHistory",bookedCustomerHistory);
    CardLayout layout = (CardLayout) container.getLayout();
    layout.next(container);
    }//GEN-LAST:event_btnTciketHistoryActionPerformed

    private void btnMngFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngFlightsActionPerformed
        // TODO add your handling code here:
        ManageFlightJPanel manageFlightJPanel= new ManageFlightJPanel(container,travelAgency);
        container.add("ManageFlightJPanel",manageFlightJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
     
    }//GEN-LAST:event_btnMngFlightsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelAgencyJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookBtn;
    private javax.swing.JButton btnManageAirliners;
    private javax.swing.JButton btnMngFlights;
    private javax.swing.JButton btnTciketHistory;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
