/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FurnitureMakerRole;

import Business.Enterprise.Enterprise;
import Business.Organization.FurnitureDeliveryOrganization;
import Business.Organization.FurnitureMakingOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DeliveryRequest;
import Business.WorkQueue.FurnitureMakingRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.FurnitureDeliveryRole.FurnitureDeliveryWorkAreaJPanel;

/**
 *
 * @author raunak
 */
public class DeliveryRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    FurnitureMakingRequest request;
    private Enterprise enterprise;
    private UserAccount userAccount;
            
    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public DeliveryRequestJPanel(JPanel userProcessContainer, FurnitureMakingRequest request,UserAccount userAccount,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount=userAccount;
        this.enterprise=enterprise;
        this.request = request;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        remarksJTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ModeofDeliveryjComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        DeliveryTypejComboBox2 = new javax.swing.JComboBox();
        estimatedDeliveryJTextField3 = new org.jdesktop.swingx.JXDatePicker();
        enterpriseLabel = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setBackground(new java.awt.Color(102, 252, 241));

        submitJButton.setBackground(new java.awt.Color(31, 40, 51));
        submitJButton.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        submitJButton.setForeground(new java.awt.Color(255, 255, 255));
        submitJButton.setText("Submit Result");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel1.setText("Remarks for Delivery");

        backJButton.setBackground(new java.awt.Color(31, 40, 51));
        backJButton.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        remarksJTextField1.setBackground(new java.awt.Color(31, 40, 51));
        remarksJTextField1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        remarksJTextField1.setForeground(new java.awt.Color(255, 255, 255));
        remarksJTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remarksJTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel2.setText("Mode of delivery");

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel3.setText("Estimated delivery date");

        ModeofDeliveryjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mini Van", "Truck", "Lorry" }));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel5.setText("Delivery type");

        DeliveryTypejComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Express Delivery", "2-Day delivery", "7-Day delivery" }));

        estimatedDeliveryJTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estimatedDeliveryJTextField3ActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        enterpriseLabel.setText("Delivery Request Form");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(remarksJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estimatedDeliveryJTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ModeofDeliveryjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeliveryTypejComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(submitJButton)))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(enterpriseLabel)
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remarksJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estimatedDeliveryJTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModeofDeliveryjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(DeliveryTypejComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        FurnitureMakerWorkAreaJPanel dwjp = (FurnitureMakerWorkAreaJPanel) component;
       /// FurnitureDeliveryWorkAreaJPanel djp = (FurnitureDeliveryWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        //djp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
  //      request.setTestResult(addressJTextField.getText());
        request.setStatus("Ready for Pickup");
        String remarks= remarksJTextField1.getText();
        Date oDate = estimatedDeliveryJTextField3.getDate();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
        try{
        String strDate = dateFormat.format(oDate); 
        String estimateDelivery= strDate;
        request.setEstimatedDelivery(estimateDelivery);
        }
        catch(NullPointerException e) 
        { 
            JOptionPane.showMessageDialog(null,"Please Fill All the Fields!!"); 
            return;
        } 
        
        String deliveryType= DeliveryTypejComboBox2.getSelectedItem().toString();
        String modeofdelivery= ModeofDeliveryjComboBox1.getSelectedItem().toString();
        if("".equals(remarks)){
            JOptionPane.showMessageDialog(null,"Please Fill All the Fields!!");
            return;
        }
        
        request.setRemarks(remarks);
        
        request.setModeofDelivery(modeofdelivery);
        request.setDeliveryType(deliveryType);
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof FurnitureDeliveryOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }     
        JOptionPane.showMessageDialog(null,"Request Submitted Succesfully!!");
//     
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void remarksJTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remarksJTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remarksJTextField1ActionPerformed

    private void estimatedDeliveryJTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estimatedDeliveryJTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estimatedDeliveryJTextField3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox DeliveryTypejComboBox2;
    private javax.swing.JComboBox ModeofDeliveryjComboBox1;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private org.jdesktop.swingx.JXDatePicker estimatedDeliveryJTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField remarksJTextField1;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
